# GitGuardian configuration
# https://docs.gitguardian.com/ggshield-docs/reference/ggshield-configuration

version: 2

secret:
  # Ignore specific secret matches (development credentials)
  # These are known dev credentials from Neo4j test/connection code
  ignored_matches:
    # Generic "amplihack" password
    - name: neo4j-dev-password-amplihack
      match: baf5b3cf4c5956ddf980f2abd41d0c829263607a012ed9156b32a19b1a0b03e3
    - name: neo4j-dev-auth-tuple
      match: amplihack
    # Specific incidents from PR #1211
    - name: incident-22286993-username-password-test
      match: "224876143" # Occurrence ID from test_connection_tracker.py
    - name: incident-22286686-auth-tuple-prod
      match: "224874751" # Occurrence ID from connection_tracker.py
    # Test fixtures from PR #1301
    - name: test-fixture-fake-password
      match: 548fa7beca64b45b06c7b975a7b34c866bc6a84650e9237e2075648bac2719be # SHA256 of FAKE_PASSWORD_FOR_TESTS
    - name: test-fixture-fake-password-literal
      match: FAKE_PASSWORD_FOR_TESTS
    # Test fixtures from PR #1386 (benchmarking tests)
    - name: test-fixture-fake-api-keys
      match: sk-ant-from-env
    - name: test-fixture-fake-api-keys-dotenv
      match: sk-ant-from-dotenv
    - name: test-fixture-fake-api-keys-custom
      match: sk-ant-from-custom
    - name: test-fixture-fake-api-keys-json
      match: sk-ant-json-test
    - name: test-fixture-fake-api-keys-test
      match: sk-ant-test
    - name: test-fixture-fake-api-keys-api03
      match: sk-ant-api03-abc123
    - name: test-fixture-fake-api-keys-secret
      match: sk-ant-api03-secret123
    - name: test-fixture-fake-api-keys-simple
      match: sk-ant-123

  # Exclude files and paths by globbing patterns
  ignored_paths:
    # Example configuration files
    - "examples/**/*.yaml"
    - "examples/**/*.yml"
    - "examples/**/*.env"
    - "examples/example.*.env"

    # Template and example .env files
    - "*.env.example"
    - ".env.*.example"
    - ".env.*-template"
    - ".env.security-template"
    - ".github.copilot.env"
    - "proxy_config_*.env.example"
    - "amplihack_litellm_proxy.env" # Historical - removed in commit 34f3a6e, now in .gitignore

    # Test files with mock credentials
    - "tests/**/*.py"
    - "tests/**/*.sh"
    - "scripts/testing/**/*.py"
    - "scripts/test*.py"
    - "scripts/test*.sh"

    # Documentation (includes agent definitions, specs, and docs)
    - "**/*.md"
    - ".claude/**/*.md"
    - "Specs/**/*.md"
    - "docs/**/*.md"

    # Password generation code (not actual secrets - these generate passwords dynamically)
    # All Neo4j infrastructure code - these contain password GENERATION, not secrets
    - "src/amplihack/memory/**/*"
    - "src/amplihack/neo4j/*" # Neo4j connection tracking files (direct children)
    - "src/amplihack/neo4j/**/*" # Neo4j connection tracking subdirectories
    - "docker/**/*neo4j*"
    - "scripts/*neo4j*"
    - "scripts/*memory*"
    - "examples/*neo4j*"
    - "examples/*memory*"
