# GitGuardian configuration
# https://docs.gitguardian.com/ggshield-docs/reference/ggshield-configuration

version: 2

secret:
  # Ignore specific secret matches (development credentials)
  # Using SHA256 hash to ignore "amplihack" - the standard dev password
  ignored_matches:
    - name: neo4j-dev-password-amplihack
      match: baf5b3cf4c5956ddf980f2abd41d0c829263607a012ed9156b32a19b1a0b03e3
    - name: neo4j-dev-auth-tuple
      match: amplihack

  # Exclude files and paths by globbing patterns
  ignored_paths:
    # Example configuration files
    - "examples/**/*.yaml"
    - "examples/**/*.yml"
    - "examples/**/*.env"
    - "examples/example.*.env"

    # Template and example .env files
    - "*.env.example"
    - ".env.*.example"
    - ".env.*-template"
    - ".env.security-template"
    - ".github.copilot.env"
    - "proxy_config_*.env.example"
    - "amplihack_litellm_proxy.env" # Historical - removed in commit 34f3a6e, now in .gitignore

    # Test files with mock credentials
    - "tests/**/*.py"
    - "tests/**/*.sh"
    - "scripts/testing/**/*.py"
    - "scripts/test*.py"
    - "scripts/test*.sh"

    # Documentation (includes agent definitions, specs, and docs)
    - "**/*.md"
    - ".claude/**/*.md"
    - "Specs/**/*.md"
    - "docs/**/*.md"

    # Password generation code (not actual secrets - these generate passwords dynamically)
    # All Neo4j infrastructure code - these contain password GENERATION, not secrets
    - "src/amplihack/memory/**/*"
    - "src/amplihack/neo4j/*"  # Neo4j connection tracking files (direct children)
    - "src/amplihack/neo4j/**/*"  # Neo4j connection tracking subdirectories
    - "docker/**/*neo4j*"
    - "scripts/*neo4j*"
    - "scripts/*memory*"
    - "examples/*neo4j*"
    - "examples/*memory*"
