[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "microsofthackathon2025-agenticcoding"
version = "0.1.0"
description = "Agentic Coding Framework for Microsoft Hackathon 2025"
requires-python = ">=3.8"
dependencies = [
    "flask>=2.0.0",
    "requests>=2.25.0",
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "aiohttp>=3.8.0",
    "litellm>=1.0.0",
    "python-dotenv>=0.19.0",
    "pathlib2>=2.3.0; python_version<'3.6'",
    "pytest-asyncio>=0.21.0",
    "cryptography>=3.4.8",
    "jinja2>=3.0.0",
    "pyyaml>=6.0.0",
    "claude-agent-sdk>=0.1.0",
]

[project.optional-dependencies]
tui-testing = [
    "pytest-asyncio>=0.21.0",
]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=22.0.0",
    "ruff>=0.1.0",
    "build>=1.0.0",  # Required for test_uvx_packaging.py
]

[project.scripts]
amplihack = "amplihack:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["amplihack*"]

[tool.setuptools.package-data]
# Include prompts and framework files
# .claude/ is handled by custom build command in setup.py
amplihack = [
    "prompts/*.md",
]

[tool.ruff]
# Essential Ruff settings only
line-length = 100
target-version = "py38"

[tool.ruff.lint]
select = ["E", "W", "F", "I"]  # Basic errors, warnings, pyflakes, isort
ignore = ["E501", "E402"]  # Line too long - handled by formatter, Module level import not at top of file

[tool.pyright]
# Essential Pyright settings only
pythonVersion = "3.8"
typeCheckingMode = "standard"
exclude = [
    "**/__pycache__",
    "**/venv",
    "**/.venv",
    "tests/**",
    "examples/**/*.py",  # Example/demo code may have missing dependencies
    ".claude/tools/test-utilities/**/*.py",  # Test utilities with missing dependencies
    "scripts/**/*.py",  # Exclude scripts from type checking
    "src/amplihack/.claude/tools/amplihack/memory/tests/test_interface.py",  # TDD tests - expected to fail
    "Specs/xpia_defense_interface.py",  # Example/demo code with intentional type issues
    "Specs/xpia_usage_examples.py",     # Example/demo code with intentional type issues
    "src/amplihack/security/cli.py",    # CLI dependencies not available in CI
]

[tool.pytest.ini_options]
# Pytest configuration
testpaths = ["tests", "src"]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test_*"]
addopts = [
    "-ra",
    "--strict-markers",
    "--tb=short",
]
# Add src directory to Python path for module discovery
pythonpath = ["src"]
# Exclude standalone test scripts from collection
norecursedirs = [".git", ".tox", "dist", "build", "*.egg"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "performance: marks tests as performance tests",
    "e2e: marks tests as end-to-end tests",
    "tui: marks tests as TUI/interactive tests",
    "gadugi: marks tests as requiring gadugi-agentic-test",
    "slow_tui: marks tests as slow TUI tests (takes >30 seconds)",
    "asyncio: marks tests as async tests",
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]
