# Stage 2 Automation Configuration
#
# Controls behavior of the automation engine that converts
# reflection insights into pull requests

# Global automation toggle
automation_enabled: true

# Priority scoring thresholds
priority:
  # Minimum score required to trigger automation
  min_score_threshold: 60

  # Score that bypasses cooldown periods
  critical_override_threshold: 150

  # Pattern type weights (higher = more important)
  weights:
    security_vulnerability: 100
    user_frustration: 80
    error_patterns: 70
    performance_bottleneck: 65
    repeated_tool_use: 60
    workflow_inefficiency: 55
    missing_feature: 50
    long_session: 40
    documentation_gap: 30

# Safety limits to prevent runaway automation
limits:
  # Maximum PRs per time period
  max_prs_per_day: 3
  max_prs_per_week: 10

  # Cooldown between automations (hours)
  cooldown_hours: 4

  # Maximum failed attempts before manual intervention
  max_failed_attempts: 5

  # Workflow timeout (minutes)
  workflow_timeout_minutes: 30

# GitHub integration settings
github:
  # Issue labels to apply
  issue_labels:
    - automated
    - improvement
    - bot-generated

  # Branch naming
  branch_prefix: "auto-improve"

  # PR settings
  pr_draft: false # Create as draft PR
  pr_auto_merge: false # Never auto-merge without review

  # Assignees for automated PRs (GitHub usernames)
  default_assignees: []

  # Reviewers to request (GitHub usernames or teams)
  default_reviewers: []

# Workflow execution
workflow:
  # Use improvement-workflow agent vs direct execution
  use_agent: true

  # Agent path
  agent_path: ".claude/agents/amplihack/improvement-workflow.md"

  # Default workflow path
  workflow_path: ".claude/workflow/DEFAULT_WORKFLOW.md"

  # Maximum retries for failed steps
  max_retries: 2

  # Constraints per improvement
  max_components: 3
  max_lines_of_code: 200

# Pattern blacklist - never automate these
blacklist:
  - database_migration
  - authentication_change
  - payment_processing
  - user_data_handling
  - deployment_config
  - security_critical
  - financial_transaction
  - pii_handling

# Context rules for automation decisions
context_rules:
  # Respect business hours (don't automate 9-5 weekdays)
  respect_business_hours: false

  # Require user approval for session
  require_user_approval: false

  # Allow automation in CI environment
  allow_ci_automation: false

  # Minimum session length (messages) before automation
  min_session_messages: 10

# Learning and adaptation
learning:
  # Track successful patterns for future priority
  track_successes: true

  # Adjust weights based on PR acceptance rate
  adaptive_weights: false

  # History retention (days)
  history_retention_days: 30

# Notification settings
notifications:
  # Slack webhook for automation events (optional)
  slack_webhook: ""

  # Email for critical automation failures (optional)
  failure_email: ""

  # Log level (debug, info, warn, error)
  log_level: "info"

# Environment-specific overrides
environments:
  development:
    automation_enabled: true
    limits:
      max_prs_per_day: 10
      cooldown_hours: 0

  testing:
    automation_enabled: true
    priority:
      min_score_threshold: 0

  production:
    automation_enabled: false # Start disabled, enable manually
    limits:
      max_prs_per_day: 1
      cooldown_hours: 12
